from __future__ import annotations

import argparse
import sys
from pathlib import Path


SCRIPT_ROOT = Path(__file__).resolve().parents[1]
if str(SCRIPT_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPT_ROOT))

from deployer.config import APP_VERSION, PROJECT_ROOT


def release_notes(version: str) -> str:
    return f"""# v{version}

## What This Release Is

`vps-3xui-oneclick-ui` is a local visual deployment tool for creating a 3x-ui VLESS TCP Reality node on your own VPS.

You provide the VPS IP, SSH user, SSH port, and VPS root password in the local page. The app handles SSH upload, remote install, 3x-ui configuration, QR generation, and local result display.

## Highlights

- Local Streamlit UI for deployment and result display.
- VLESS Reality QR code and `vless://` link fallback.
- Subscription link and subscription QR display when available.
- 3x-ui panel address, account, and password shown after deployment.
- Local management mode for existing successful results.
- Public diagnostics package that excludes node links, QR images, panel credentials, and VPS root passwords.
- Local non-secret profiles for common VPS and node settings.
- Experimental desktop launcher and PyInstaller packaging scaffolds.
- Current-state summary, first-run checklist, and failure recovery guidance.
- SHA256 checksum and release manifest generation for release integrity.
- Tag-triggered GitHub Release publishing workflow.
- One-command release readiness checks before tagging.
- Changelog validation in release readiness checks.
- Tracked-file secret hygiene checks for release safety.
- Optional pre-commit hook for tracked-file secret hygiene.
- Privacy and data-boundary documentation for local files, SSH actions, and diagnostics.
- No-VPS Streamlit UI smoke test in release readiness.
- One-command local project doctor for health checks.
- Standalone release artifact verifier for source zip, checksums, and manifest.
- Version consistency check for release metadata.
- Local release preparation command that prints upload artifacts.
- Sidebar release package status panel for local release readiness visibility.
- Sidebar download buttons for generated release artifacts.
- Local version bump helper for APP_VERSION, CHANGELOG, and RELEASE metadata.
- Open-source metadata readiness checks for docs, issue templates, and workflows.
- Release manifest source provenance with Git commit, branch, and dirty state.
- Sidebar release provenance display for generated release artifacts.
- Sidebar warning for release artifacts built from a dirty worktree.
- Command-line warning when preparing release artifacts from a dirty worktree.
- Sidebar warning for release artifacts built from an older Git commit.
- Command-line stale release artifact validation against local Git HEAD.
- Release manifest artifact size and checksum validation.
- Release manifest project, timestamp, and safety metadata validation.
- Product readiness checker for open-source MVP gates and remaining desktop product gaps.
- Portable product package with START_HERE guidance and product readiness report.
- Streamlit release panel downloads for portable product package and product readiness report.
- Release manifest and SHA256 coverage for product package artifacts.
- Portable launch preflight checks for Python, virtual environment setup, dependency installation, and product readiness.
- Desktop launcher runtime validation and local-only environment overrides.
- Double-click macOS portable launcher through `start_macos.command`.
- Dedicated portable launcher validation for Windows, macOS, and Linux startup files.
- Chinese portable quick-start guide through `START_HERE.zh-CN.md`.
- Extracted portable package acceptance check that simulates a downloaded user package.
- Stronger PyInstaller desktop artifact validation after macOS and Windows builds.
- Cross-platform GitHub Actions product CI for Ubuntu, macOS, and Windows.
- Experimental unsigned macOS and Windows desktop artifacts through GitHub Actions.
- Sidebar GitHub Release update checker that is explicit, read-only, and does not connect to a VPS.
- Guarded local release tag preparation helper for GitHub Release publishing.
- Guarded remote reset with typed confirmation, remote backup, local output clearing, and optional 3x-ui stop-and-archive.
- Manual VPS compatibility test worksheet generated with release artifacts.
- Machine-readable update manifest for future update-channel tooling.
- Signing readiness report for macOS notarization and Windows signing preparation.
- Experimental Inno Setup Windows installer scaffold for future signed installer releases.
- Signed artifact validation report for future macOS and Windows signed release outputs.
- Go-live readiness report summarizing final release blockers.

## Download

Attach the release and product artifacts generated by:

```bash
python3 scripts/build_release_bundle.py
```

Expected artifacts:

```text
dist/vps-3xui-oneclick-ui-v{version}.zip
dist/vps-3xui-oneclick-ui-portable-v{version}.zip
dist/GITHUB_RELEASE_v{version}.md
dist/SHA256SUMS_v{version}.txt
dist/release-manifest-v{version}.json
dist/PRODUCT_READINESS_v{version}.md
dist/VPS_COMPATIBILITY_TEST_v{version}.md
dist/update-manifest-v{version}.json
dist/SIGNING_READINESS_v{version}.md
dist/SIGNED_ARTIFACT_VALIDATION_v{version}.md
dist/GO_LIVE_READINESS_v{version}.md
```

The portable zip includes both `START_HERE.md` and `START_HERE.zh-CN.md`.

## Quick Start

Windows:

```text
start_windows.bat
```

macOS / Linux:

Double-click on macOS:

```text
start_macos.command
```

Terminal fallback:

```bash
chmod +x start_mac_linux.sh
./start_mac_linux.sh
```

Experimental desktop launcher:

```bash
python3 desktop_launcher.py
```

## Safety Notes

- VPS root passwords are only kept in the current local app session.
- VPS root passwords are not written to project files, logs, release zips, Git, or `output/`.
- Local `output/` files can contain node links, QR images, subscription links, and panel information. Treat exported result zips as sensitive.
- Local `data/profiles.json` contains non-password profile settings and is excluded from Git and release zips.
- See `docs/privacy.md` for local data, VPS data, diagnostics, and release-check boundaries.
- The update checker only reads GitHub Release metadata and does not upload diagnostics or install updates.
- The update manifest describes release assets and checksums, but does not auto-install anything.
- Signing readiness reports do not include signing passwords, certificates, or app-specific passwords.
- Signed artifact validation reports do not contain signing secrets or certificate private keys.
- Go-live readiness reports summarize status only and do not include secrets or deployment outputs.
- Windows installer outputs are experimental and must be labeled unsigned until code signing is implemented.
- Server hardening remains opt-in.
- Remote reset remains opt-in and requires the exact confirmation phrase `RESET_3XUI_ONECLICK`.
- The first version does not default-disable root login, password login, or ping.

## Changelog

See `CHANGELOG.md` in the release zip for the project history.

## Release Validation

Before publishing, run:

```bash
python3 -m py_compile app.py deployer/*.py scripts/*.py
python3 -m py_compile desktop_launcher.py desktop/check_desktop_package.py
bash -n remote_scripts/preflight_remote.sh
bash -n remote_scripts/install_remote.sh
bash -n remote_scripts/harden_after_success.sh
bash -n start_macos.command
bash -n desktop/build_macos_app.sh
python3 scripts/check_streamlit_app.py
python3 scripts/check_release_ready.py
python3 scripts/check_release_artifacts.py
python3 scripts/check_version_consistency.py
python3 scripts/check_open_source_ready.py
python3 scripts/check_product_readiness.py
python3 scripts/check_portable_launchers.py
python3 scripts/build_product_package.py
python3 scripts/check_product_package.py
python3 scripts/check_portable_user_package.py
python3 scripts/doctor.py --release
python3 scripts/prepare_release.py --allow-dirty
python3 scripts/prepare_release_tag.py --skip-checks
python3 desktop/check_desktop_package.py --release-zip dist/vps-3xui-oneclick-ui-v{version}.zip
python3 desktop/check_desktop_package.py --built-artifact "dist/VPS 3x-ui Oneclick.app"
```

Do not run a real VPS deployment during release validation unless that is the explicit test goal.
Confirm the latest GitHub Actions `Static checks` run is green before publishing a formal GitHub Release.
Only attach desktop artifacts when the GitHub Actions `Desktop build` workflow is green, and label them as unsigned experimental builds.
"""


def write_release_notes(version: str) -> Path:
    dist_dir = PROJECT_ROOT / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)
    notes_path = dist_dir / f"GITHUB_RELEASE_v{version}.md"
    notes_path.write_text(release_notes(version), encoding="utf-8")
    return notes_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a GitHub Release draft without secrets.")
    parser.add_argument("--version", default=APP_VERSION)
    args = parser.parse_args()
    notes_path = write_release_notes(args.version)
    print(notes_path)


if __name__ == "__main__":
    main()
